version: '{build}'
image:
  - Visual Studio 2017
  - Ubuntu
skip_commits:
  files:
    - '*.md'
    - '*.txt'
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
skip_tags: true
install:
- sh: wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
- sh: sudo dpkg -i packages-microsoft-prod.deb
- sh: sudo apt-get install apt-transport-https
- sh: sudo apt-get update
- sh: sudo apt-get install -y --allow-downgrades dotnet-sdk-2.1=2.1.403-1
build_script:
- ps: >-
    $id = $env:APPVEYOR_REPO_COMMIT_TIMESTAMP -replace '([-:]|\.0+Z)', ''

    $id = $id.Substring(0, 13)

    if ($isWindows) { .\pack.cmd ci-$id } else { ./pack.sh ci-$id }
test_script:
- ps: |
      if ($isWindows) {
          .\test.cmd
      } else {
          ./test.sh
          # revert to following post merge of PR codecov/codecov-bash#138
          # curl -s https://codecov.io/bash > codecov
          curl -s https://raw.githubusercontent.com/codecov/codecov-bash/14662d32a4862918c31efafe4b450de1305a38e1/codecov > codecov
          chmod +x codecov
          ./codecov -f ./tests/coverage.opencover.xml
      }
artifacts:
- path: dist\*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/raboof/api/v2/package
  api_key:
    secure: fhGwXyO35FSshRzs5GWmF1LJTrd1sIqmS/jNCSfO2LfOciuYAKiXuFMYZFGiTAl+
  symbol_server: https://www.myget.org/F/raboof/symbols/api/v2/package
  on:
    branch: master
notifications:
- provider: Email
  to:
  - raboof-ci@googlegroups.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
